Hw06 email
Serhii-Pradid/nodejs-homework-api pull request #5
Opened 2023-08-17 11:44 UTC by Serhii-Pradid

Перевірте будь-ласка

2023-08-18 21:01 UTC, ceREAL133 approved these changes

2023-08-18 21:01 UTC, ceREAL133 commented on controllers/auth-controller.js
> +        await User.findByIdAndUpdate(user._id, {verify: true, verificationToken: "" })
verificationToken should be null

2023-08-18 21:02 UTC, ceREAL133 requested changes

2023-08-18 21:02 UTC, ceREAL133 commented on controllers/auth-controller.js
> +        await User.findByIdAndUpdate(user._id, {verify: true, verificationToken: "" })
verificationToken should be null

2023-08-19 05:57 UTC, Serhii-Pradid commented on controllers/auth-controller.js
> +        await User.findByIdAndUpdate(user._id, {verify: true, verificationToken: "" })
corrected

2023-08-19 06:51 UTC, ceREAL133 approved these changes

2023-08-19 07:15 UTC, merged